### ISSUE TITLE
About the meaning of Input data

### ISSUE THREAD

**Issue by LlongXie** [lidargait/lidargait.github.io#1]
LidarGait's input.shape = ([64, 10, 3, 64, 64])-->([n, s, c, H, W])
May I ask why the channel is 3? Because I think the channel of depth image may be 1.
Sincerely thanks for your help.

**Comment by chuanfushen** [comment]
Sorry for my late response since the vocation. As mentioned in the paper, the depth projection is normalized
and converted to RGB images from the 1-channel images.

**Comment by LlongXie** [comment]
Got it. I misunderstood that 3-channel of range image refer to range, azimuth and inclination. Just treat it as RGB-like image is OK, ha? And thank you for your busy reply.
